version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    env_file: .env

  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'www.ドメイン名 -> http://wordpress'
      STAGE: 'production'
      FORCE_RENEW: 'true'
    volumes:
      - ./certs:/var/lib/https-portal

volumes:
  db_data:
